# Specify the version for docker-compose.yml
version: "3.8"

# add the serivces needed (postgres,go)
services:
  database:
    container_name: database
    image: postgres:latest
    environment:
      POSTGRES_USER: pg
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: crud
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

#  go:
#    container_name: go
#    # build the Dockerfile, alternatively use an image.
#    build:
#      context: .
#    depends_on:
#      - "database"

volumes:
  db: # create the volume for persisting data.
            